name: Prepare Deployment
description: Extracts Data to will feed deployment

outputs:
  matrix:
    description: Matrix containing Environment and Target for deployment 
    value: ${{ steps.matrix.outputs.matrix}}
  is-valid-environment:
    description: Validates Deployment Enviroment ( development, staging, production )
    value: ${{ steps.validator.outputs.environment }}
  is-valid-lambdas-deployment:
    description: Validates Lambdas Deployment
    value: ${{ steps.validator.outputs.lambda }}
  is-valid-api-deployment:
    description: Validates API Deployment
    value: ${{ steps.validator.outputs.api }}

runs:
  using: composite
  steps:
    # Parse Comment
    - name: Get PR comment
      uses: actions-ecosystem/action-regex-match@v2
      id: get-pr-comment
      with:
        text: ${{ github.event.comment.body }}
        regex: '^(deploy) (lambdas|api) (development|staging|production)$'
      
    - name: Extract Environment
      id: matrix
      shell: bash
      run: |
        echo "matrix=[{ \"target\" : [\"${{ steps.get-pr-comment.outputs.group2 }}\"], \"environment\": [\"${{ steps.get-pr-comment.outputs.group3 }}\"] }]" >> "$GITHUB_OUTPUT"

    - name: Extract Validator
      id: validator
      shell: bash
      run: |
        echo "environment=${{ fromJSON(env.ACCOUNT_MAPPING)[steps.get-pr-comment.outputs.group3] != '' }}" >> "$GITHUB_OUTPUT"
        echo "lambda=${{ steps.get-pr-comment.outputs.group2 == 'lambdas' }}" >> "$GITHUB_OUTPUT"
        echo "api=${{ steps.get-pr-comment.outputs.group2 == 'api' }}" >> "$GITHUB_OUTPUT"
