name: Deploy

on:
  issue_comment:
    types: [created]
env:
  mapping: '{"development": "111", "staging": "222", "production": "333"}'

jobs:

  # Extracts Enviroment / Target from PR Comment
  prepare-data:
    outputs:
      matrix: ${{ steps.extract-data.outputs.matrix }}
      is-valid-environment: ${{ steps.extract-data.outputs.is-valid-environment }}
      is-valid-lambdas-deployment: ${{ steps.extract-data.outputs.is-valid-lambdas-deployment }}
      is-valid-api-deployment: ${{ steps.extract-data.outputs.is-valid-api-deployment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-prepare
        id: extract-data

  validate-deployment:
    runs-on: ubuntu-latest
    needs: prepare-data
    steps:
      - uses: actions/checkout@v3

      - name: Early Quit
        if: (needs.prepare-data.outputs.is-valid-lambdas-deployment != 'true' && needs.prepare-data.outputs.is-valid-api-deployment != 'true') || !needs.prepare-data.outputs.is-valid-environment
        run: exit 1

      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '' # no trigger cause at this point we are already valid
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          

  # Deploy Lambdas
  deploy-lambdas:
    needs: [prepare-data, validate-deployment]
    strategy:
      matrix:
        target: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].environment }}
    if: needs.prepare-data.outputs.is-valid-lambdas-deployment == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo 'account: ${{fromJSON(env.mapping)[matrix.environment]}}'

  # Deploy Lambdas
  deploy-api:
    needs: [prepare-data, validate-deployment]
    strategy:
      matrix:
        target: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].environment }}
    if: needs.prepare-data.outputs.is-valid-api-deployment == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3