name: Deploy

on:
  issue_comment:
    types: [created]
env:
  mapping: '{"development": "111", "staging": "222", "production": "333"}'

jobs:

  # Extracts Enviroment / Target from PR Comment
  extract-data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix}}
    steps:
    
    # Parse Comment
    - name: Get PR comment
      uses: actions-ecosystem/action-regex-match@v2
      id: get-pr-comment
      with:
        text: ${{ github.event.comment.body }}
        regex: '^(deploy) (lambdas|api) (development|staging|production)$'
      
    # Output for Matrix
    - name: Extract Environment
      id: matrix
      run: |
        echo "matrix=[{ \"target\" : [\"${{ steps.get-pr-comment.outputs.group2 }}\"], \"environment\": [\"${{ steps.get-pr-comment.outputs.group3 }}\"] }]" >> "$GITHUB_OUTPUT"
  

  # Deploy Lambdas
  deploy-lambdas:
    needs: extract-data
    strategy:
      matrix:
        target: ${{ fromJSON(needs.extract-data.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.extract-data.outputs.matrix)[0].environment }}
    if: fromJSON(needs.extract-data.outputs.matrix)[0].target[0] == 'lambdas'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo ${{ fromJSON(needs.extract-data.outputs.matrix).target }} 
          echo 'env: ${{fromJSON(env.mapping)}}'
          echo 'account: ${{fromJSON(env.mapping)[matrix.environment]}}'

  # Deploy Lambdas
  deploy-api:
    needs: extract-data
    strategy:
      matrix: ${{ fromJSON(needs.extract-data.outputs.matrix) }}
    if: fromJSON(needs.extract-data.outputs.matrix)[0].target[0] == 'api'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3