name: Deploy

on:
  issue_comment:
    types: [created]

jobs:

  # Deploy Lambdas
  deploy-lambdas:
    strategy:
      matrix:
        environment: [ # env variables are not available within matrix definition, might need to output the vars
          { name: "development", aws_account_id: 'a' },
          { name: "staging", aws_account_id: 'b' },
          { name: "production", aws_account_id: 'c' }
         ]
    runs-on: ubuntu
    if: github.event.issue.pull_request && (github.event.comment.body == 'deploy lambdas development')
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3