name: Deploy

on:
  issue_comment:
    types: [created]

env:
  LAMBDA_TF_PATH: 'lambdas/availability/infra'
  LAMBDA_TF_VERSION: 1.1.7

jobs:

  # Deploy Lambdas
  deploy-lambdas:
    strategy:
      matrix:
        environment: [ # env variables are not available within matrix definition, might need to output the vars
          { name: "development", aws_account_id: '202971816376' },
          { name: "staging", aws_account_id: '015319854171' },
          { name: "production", aws_account_id: '603510970537' }
         ]
    runs-on: [self-hosted, "${{ matrix.environment.name }}"]
    if: github.event.issue.pull_request && (github.event.comment.body == 'deploy lambdas development')
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3