name: Deploy

on:
  issue_comment:
    types: [created]

jobs:

  # Extracts Enviroment / Target from PR Comment
  extract-data:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.environment.outputs.environment}}
      target: ${{ steps.environment.outputs.target}}
    steps:
    
    - name: Get PR comment
      uses: actions-ecosystem/action-regex-match@v2
      id: get-pr-comment
      with:
        text: ${{ github.event.comment.body }}
        regex: '^(deploy) (lambdas|api) (development|staging|production)$'
        
    - name: Extract Environment
      id: target
      run: |
        echo "target=${{ steps.get-pr-comment.outputs.group3 }}" >> "$GITHUB_OUTPUT"

    - name: Extract Target
      id: environment
      run: |
        echo "environment=${{ steps.get-pr-comment.outputs.group3 }}" >> "$GITHUB_OUTPUT"

  

  # Deploy Lambdas
  deploy-lambdas:
    needs: extract-data
    strategy:
      matrix:
        environment: ${{ toJSON(needs.extract-data.outputs.environment) }}
        target: ${{ toJSON(needs.extract-data.outputs.target) }}
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && (github.event.comment.body == 'deploy lambdas development')
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3