name: Deploy

on:
  issue_comment:
    types: [created]
env:
  mapping: '{"development": "111", "staging": "222", "production": "333"}'

jobs:

  # Extracts Enviroment / Target from PR Comment
  prepare-data:
    outputs:
      matrix: ${{ steps.extract-data.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-prepare
        id: extract-data
      

  # Deploy Lambdas
  deploy-lambdas:
    needs: prepare-data
    strategy:
      matrix:
        target: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].environment }}
    # if: needs.prepare-data.outputs.is-valid-lambda-deployment == 'true' && needs.prepare-data.outputs.is-valid-environment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo ${{ needs.prepare-data.outputs.is-valid-environment }} 
          echo ${{ needs.prepare-data.outputs.is-valid-api-deployment }} 
          echo ${{ needs.prepare-data.outputs.is-valid-lambda-deployment }} 
          echo ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].target[0] }} 
          echo 'env: ${{fromJSON(env.mapping)}}'
          echo 'account: ${{fromJSON(env.mapping)[matrix.environment]}}'

  # Deploy Lambdas
  deploy-api:
    needs: prepare-data
    strategy:
      matrix:
        target: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.prepare-data.outputs.matrix)[0].environment }}
    if: needs.prepare-data.outputs.is-valid-api-deployment == 'true' && needs.prepare-data.outputs.is-valid-environment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      deployments: write
      checks: read
      statuses: write
    steps:
    
      # Checkout
      - uses: actions/checkout@v3