name: Deploy

on:
  issue_comment:
    types: [created]
env:
  ACCOUNT_MAPPING: '{"development": "111", "staging": "222", "production": "333"}'

permissions:
  pull-requests: write

jobs:

  # Extracts Enviroment / Target from PR Comment
  validate-deployment:
    outputs:
      matrix: ${{ steps.extract-data.outputs.matrix }}
      is-valid-environment: ${{ steps.extract-data.outputs.is-valid-environment }}
      is-valid-lambdas-deployment: ${{ steps.extract-data.outputs.is-valid-lambdas-deployment }}
      is-valid-api-deployment: ${{ steps.extract-data.outputs.is-valid-api-deployment }}
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'deploy')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-prepare
        id: extract-data
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          account_mapping: ${{ env.ACCOUNT_MAPPING }}

  # Deploy Lambdas
  deploy-lambdas:
    needs: [validate-deployment]
    strategy:
      matrix:
        target: ${{ fromJSON(needs.validate-deployment.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.validate-deployment.outputs.matrix)[0].environment }}
    # if: needs.validate-deployment.outputs.is-valid-lambdas-deployment == 'true'
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo 'account: ${{fromJSON(env.ACCOUNT_MAPPING)[matrix.environment]}}'
          echo ${{needs.validate-deployment.outputs.is-valid-lambdas-deployment}}
          echo ${{needs.validate-deployment.outputs.is-valid-api-deployment}}
          echo ${{needs.validate-deployment.outputs.is-valid-environment}}

  # Deploy Lambdas
  deploy-api:
    needs: [validate-deployment]
    strategy:
      matrix:
        target: ${{ fromJSON(needs.validate-deployment.outputs.matrix)[0].target }}
        environment: ${{ fromJSON(needs.validate-deployment.outputs.matrix)[0].environment }}
    if: needs.validate-deployment.outputs.is-valid-api-deployment == 'true'
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - uses: actions/checkout@v3